apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: dc-metro
  name: nodejs
  namespace: deboerrh
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nodejs
status:
  loadBalancer: {}
